create extension if not exists pgcrypto;

create table if not exists public.rifa_configuracao (
    id integer primary key check (id = 1),
    nome_rifa text not null default 'Rifa Solidária',
    premio text not null default '',
    chave_pix text not null default 'rifa@exemplo.com.br',
    valor_bilhete numeric(10, 2) not null default 10.00 check (valor_bilhete > 0),
    quantidade_premios integer not null default 1 check (quantidade_premios between 1 and 1000),
    quantidade_vendedores integer not null default 1 check (quantidade_vendedores between 1 and 100),
    bilhetes_impressos integer not null default 20 check (bilhetes_impressos >= 0),
    bilhetes_online integer not null default 20 check (bilhetes_online >= 0),
    atualizado_em timestamptz not null default now()
);

insert into public.rifa_configuracao (id) values (1) on conflict (id) do nothing;

create table if not exists public.rifa_vendedores (
    id bigint generated by default as identity primary key,
    nome text not null,
    codigo_ref text not null unique,
    ativo boolean not null default true,
    criado_em timestamptz not null default now()
);

create table if not exists public.rifa_perfis (
    auth_user_id uuid primary key references auth.users(id) on delete cascade,
    login text not null unique,
    perfil text not null check (perfil in ('admin', 'vendedor')),
    vendedor_id bigint references public.rifa_vendedores(id) on delete set null,
    criado_em timestamptz not null default now(),
    check ((perfil = 'admin' and vendedor_id is null) or (perfil = 'vendedor' and vendedor_id is not null))
);

create table if not exists public.rifa_bilhetes (
    id bigint generated by default as identity primary key,
    numero integer not null unique,
    vendedor_id bigint not null references public.rifa_vendedores(id),
    tipo text not null check (tipo in ('impresso', 'online')),
    status text not null default 'disponivel' check (status in ('disponivel', 'pago')),
    nome_comprador text,
    telefone_comprador text,
    data_venda timestamptz,
    criado_em timestamptz not null default now()
);

create index if not exists rifa_bilhetes_vendedor_idx on public.rifa_bilhetes (vendedor_id, numero);

create table if not exists public.rifa_reservas (
    bilhete_id bigint primary key references public.rifa_bilhetes(id) on delete cascade,
    nome_comprador text not null,
    telefone_comprador text not null,
    criado_em timestamptz not null default now()
);

create table if not exists public.rifa_sorteios (
    id bigint generated by default as identity primary key,
    bilhete_id bigint not null,
    numero_bilhete integer not null,
    nome_vencedor text not null,
    telefone_vencedor text,
    nome_vendedor text not null,
    grupo_sorteio uuid not null,
    premio_numero integer not null check (premio_numero > 0),
    total_bilhetes_pagos integer not null,
    realizado_em timestamptz not null default now(),
    renovado boolean not null default false,
    unique (grupo_sorteio, premio_numero),
    unique (grupo_sorteio, bilhete_id)
);

create index if not exists rifa_sorteios_grupo_idx on public.rifa_sorteios (grupo_sorteio, premio_numero);

alter table public.rifa_configuracao enable row level security;
alter table public.rifa_vendedores enable row level security;
alter table public.rifa_perfis enable row level security;
alter table public.rifa_bilhetes enable row level security;
alter table public.rifa_reservas enable row level security;
alter table public.rifa_sorteios enable row level security;

revoke all on public.rifa_configuracao, public.rifa_vendedores, public.rifa_perfis,
    public.rifa_bilhetes, public.rifa_reservas, public.rifa_sorteios from anon, authenticated;
grant all on public.rifa_configuracao, public.rifa_vendedores, public.rifa_perfis,
    public.rifa_bilhetes, public.rifa_reservas, public.rifa_sorteios to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.rifa_inicializar_bilhetes()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    configuracao public.rifa_configuracao%rowtype;
    quantidade_atual integer;
    vendedor public.rifa_vendedores%rowtype;
    numero_atual integer;
    indice integer;
begin
    select * into configuracao from public.rifa_configuracao where id = 1 for update;
    select count(*) into quantidade_atual from public.rifa_vendedores where ativo;

    while quantidade_atual < configuracao.quantidade_vendedores loop
        insert into public.rifa_vendedores (nome, codigo_ref)
        values ('Vendedor ' || (quantidade_atual + 1), 'v' || (quantidade_atual + 1))
        on conflict (codigo_ref) do update set ativo = true;
        quantidade_atual := quantidade_atual + 1;
    end loop;

    if not exists (select 1 from public.rifa_bilhetes) then
        numero_atual := 1;
        for vendedor in
            select * from public.rifa_vendedores where ativo order by id limit configuracao.quantidade_vendedores
        loop
            for indice in 1..configuracao.bilhetes_impressos + configuracao.bilhetes_online loop
                insert into public.rifa_bilhetes (numero, vendedor_id, tipo)
                values (
                    numero_atual,
                    vendedor.id,
                    case when indice <= configuracao.bilhetes_impressos then 'impresso' else 'online' end
                );
                numero_atual := numero_atual + 1;
            end loop;
        end loop;
    end if;
end;
$$;

create or replace function public.rifa_reservar_bilhete(
    p_bilhete_id bigint,
    p_nome text,
    p_telefone text,
    p_perfil text,
    p_vendedor_id bigint default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    bilhete public.rifa_bilhetes%rowtype;
begin
    if exists (select 1 from public.rifa_sorteios where not renovado) then
        raise exception 'Sorteio realizado. Aguarde a renovação das rifas para fazer novas reservas.' using errcode = 'P0001';
    end if;

    select * into bilhete from public.rifa_bilhetes where id = p_bilhete_id for update;
    if not found or bilhete.status <> 'disponivel'
        or (p_perfil = 'vendedor' and bilhete.vendedor_id <> p_vendedor_id)
        or exists (select 1 from public.rifa_reservas where bilhete_id = p_bilhete_id) then
        raise exception 'Este bilhete não está disponível.' using errcode = 'P0001';
    end if;

    update public.rifa_bilhetes
    set nome_comprador = p_nome,
        telefone_comprador = p_telefone,
        data_venda = now(),
        status = 'disponivel'
    where id = p_bilhete_id;

    insert into public.rifa_reservas (bilhete_id, nome_comprador, telefone_comprador)
    values (p_bilhete_id, p_nome, p_telefone);
    return 'Bilhete reservado.';
end;
$$;

create or replace function public.rifa_confirmar_pagamento(p_bilhete_id bigint, p_vendedor_id bigint default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    linhas_afetadas integer;
begin
    if exists (select 1 from public.rifa_sorteios where not renovado) then
        raise exception 'O sorteio já foi feito. Renove as rifas antes de confirmar outros pagamentos.' using errcode = 'P0001';
    end if;

    update public.rifa_bilhetes
    set status = 'pago'
    where id = p_bilhete_id
      and status <> 'pago'
      and (p_vendedor_id is null or vendedor_id = p_vendedor_id);
    get diagnostics linhas_afetadas = row_count;
    if linhas_afetadas <> 1 then
        raise exception 'Bilhete não encontrado ou já pago.' using errcode = 'P0001';
    end if;
    delete from public.rifa_reservas where bilhete_id = p_bilhete_id;
end;
$$;

create or replace function public.rifa_sortear()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    configuracao public.rifa_configuracao%rowtype;
    total_pago integer;
    sorteio_grupo uuid := gen_random_uuid();
    bilhete record;
    premio_numero integer := 0;
    resultados jsonb := '[]'::jsonb;
begin
    select * into configuracao from public.rifa_configuracao where id = 1 for update;
    if exists (select 1 from public.rifa_sorteios where not renovado) then
        raise exception 'O sorteio atual já foi realizado. Limpe os bilhetes antes de iniciar outro.' using errcode = 'P0001';
    end if;

    select count(*) into total_pago from public.rifa_bilhetes where status = 'pago';
    if total_pago = 0 then
        raise exception 'Não há bilhetes pagos para participar do sorteio.' using errcode = 'P0001';
    end if;
    if total_pago < configuracao.quantidade_premios then
        raise exception 'A quantidade de bilhetes pagos é menor que a quantidade de prêmios configurada.' using errcode = 'P0001';
    end if;

    for bilhete in
        select b.id, b.numero, b.nome_comprador, b.telefone_comprador, v.nome as nome_vendedor
        from public.rifa_bilhetes b
        left join public.rifa_vendedores v on v.id = b.vendedor_id
        where b.status = 'pago'
        order by gen_random_uuid()
        limit configuracao.quantidade_premios
        for update of b
    loop
        premio_numero := premio_numero + 1;
        insert into public.rifa_sorteios (
            bilhete_id, numero_bilhete, nome_vencedor, telefone_vencedor,
            nome_vendedor, grupo_sorteio, premio_numero, total_bilhetes_pagos
        ) values (
            bilhete.id, bilhete.numero, coalesce(nullif(bilhete.nome_comprador, ''), 'Nome não cadastrado'),
            bilhete.telefone_comprador, coalesce(bilhete.nome_vendedor, 'Vendedor'),
            sorteio_grupo, premio_numero, total_pago
        );
        resultados := resultados || jsonb_build_array(jsonb_build_object(
            'id', currval(pg_get_serial_sequence('public.rifa_sorteios', 'id')),
            'numero_bilhete', bilhete.numero,
            'nome_vencedor', coalesce(nullif(bilhete.nome_comprador, ''), 'Nome não cadastrado'),
            'telefone_vencedor', bilhete.telefone_comprador,
            'nome_vendedor', coalesce(bilhete.nome_vendedor, 'Vendedor'),
            'premio_numero', premio_numero,
            'total_bilhetes_pagos', total_pago,
            'renovado', false
        ));
    end loop;

    return jsonb_build_object('sorteios', resultados);
end;
$$;

create or replace function public.rifa_renovar()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    perform 1 from public.rifa_sorteios where not renovado for update;
    if not found then
        raise exception 'Faça o sorteio antes de limpar e renovar os bilhetes.' using errcode = 'P0001';
    end if;
    update public.rifa_bilhetes
    set status = 'disponivel', nome_comprador = null, telefone_comprador = null, data_venda = null;
    delete from public.rifa_reservas;
    update public.rifa_sorteios set renovado = true where not renovado;
end;
$$;

revoke all on function public.rifa_inicializar_bilhetes() from public, anon, authenticated;
revoke all on function public.rifa_reservar_bilhete(bigint, text, text, text, bigint) from public, anon, authenticated;
revoke all on function public.rifa_confirmar_pagamento(bigint, bigint) from public, anon, authenticated;
revoke all on function public.rifa_sortear() from public, anon, authenticated;
revoke all on function public.rifa_renovar() from public, anon, authenticated;
grant execute on function public.rifa_inicializar_bilhetes() to service_role;
grant execute on function public.rifa_reservar_bilhete(bigint, text, text, text, bigint) to service_role;
grant execute on function public.rifa_confirmar_pagamento(bigint, bigint) to service_role;
grant execute on function public.rifa_sortear() to service_role;
grant execute on function public.rifa_renovar() to service_role;
